FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements-flake8-black.txt .
RUN pip install -r requirements-flake8-black.txt

# Command to run the application
CMD ["python", "app.py"]