# Use a lightweight Python image
FROM python:3.10-slim

# Set the working directory
WORKDIR /geopandasapp

# Install dependencies
RUN apt-get update && apt-get install -y \
    gdal-bin \
    && rm -rf /var/lib/apt/lists/*

# Install Python packages
RUN pip install --no-cache-dir geopandas pandas shapely fiona pyproj rtree

# Keep the container running (optional, if you want to exec commands later)
CMD ["tail", "-f", "/dev/null"]
