# ----------------------------
# Base image
# ----------------------------
FROM python:3.11-slim

# ----------------------------
# Build arguments
# ----------------------------
ARG FLASK_PROCESS_USER=runner
ARG FLASK_PROCESS_USER_ID=1000
ARG FLASK_PROCESS_GROUP_ID=1000
ARG ENVIRONMENT=production
ENV ENVIRONMENT=${ENVIRONMENT}

# ----------------------------
# Install system dependencies
# ----------------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    python3-dev \
    default-jdk \
    libmariadb-dev \
    libmariadb-dev-compat \
    libpango-1.0-0 \
    libcairo2 \
    libffi-dev \
    libpangocairo-1.0-0 \
    zlib1g-dev \
    bzip2 \
    xz-utils \
    wget \
    unzip \
    curl \
    git \
    rclone \
    perl \
    pkg-config \
    poppler-utils \
    && rm -rf /var/lib/apt/lists/*


# ----------------------------
# Upgrade pip, setuptools, wheel
# ----------------------------
RUN pip install --upgrade pip setuptools wheel

# ----------------------------
# Install vsearch
# ----------------------------
RUN wget https://github.com/torognes/vsearch/releases/download/v2.30.0/vsearch-2.30.0-linux-x86_64.tar.gz && \
    tar -xzf vsearch-2.30.0-linux-x86_64.tar.gz && \
    mv vsearch-2.30.0-linux-x86_64/bin/vsearch /usr/local/bin/ && \
    chmod +x /usr/local/bin/vsearch && \
    rm -rf vsearch-2.30.0-linux-x86_64 vsearch-2.30.0-linux-x86_64.tar.gz

# ----------------------------
# Install FastQC
# ----------------------------
WORKDIR /usr/local/bin
RUN wget https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.12.1.zip -O fastqc.zip && \
    unzip fastqc.zip && \
    chmod +x FastQC/fastqc && \
    ln -s /usr/local/bin/FastQC/fastqc /usr/local/bin/fastqc && \
    rm fastqc.zip

# Add FastQC to PATH
ENV PATH="/usr/local/bin/FastQC:${PATH}"

# ----------------------------
# Create non-root user
# ----------------------------
RUN groupadd -g $FLASK_PROCESS_GROUP_ID $FLASK_PROCESS_USER && \
    useradd -m -u $FLASK_PROCESS_USER_ID -g $FLASK_PROCESS_GROUP_ID $FLASK_PROCESS_USER

# ----------------------------
# Set working directory
# ----------------------------
WORKDIR /app
ENV PYTHONPATH=/app

# Change ownership of /app to non-root user
RUN chown -R $FLASK_PROCESS_USER:$FLASK_PROCESS_GROUP_ID /app

# ----------------------------
# Copy requirements and install
# ----------------------------
COPY requirements.txt .
RUN pip install --trusted-host pypi.python.org -r requirements.txt
ENV PATH="$PATH:/home/$FLASK_PROCESS_USER/.local/bin"

# ----------------------------
# Switch to non-root user
# ----------------------------
USER $FLASK_PROCESS_USER

# ----------------------------
# Run the Flask app with Gunicorn
# ----------------------------
CMD exec gunicorn --bind 0.0.0.0:56733 app:app --workers ${GUNICORN_WORKERS:-2} --threads 2 ${GUNICORN_RELOAD:-}
