"""Create tables for v2 sequencing upload

Revision ID: 0067468deeec
Revises: 37c0420b998d
Create Date: 2024-07-08 12:48:41.670737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0067468deeec'
down_revision: Union[str, None] = '37c0420b998d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequencing_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.String(length=250), nullable=True),
    sa.Column('latest_metadata_filename', sa.String(length=255), nullable=True),
    sa.Column('final_metadata_filename', sa.String(length=255), nullable=True),
    sa.Column('uploads_folder', sa.String(length=20), nullable=True),
    sa.Column('sequencing_upload_filedata', mysql.JSON(none_as_null=True), nullable=True),
    sa.Column('Country', sa.String(length=255), nullable=True),
    sa.Column('Sequencing_platform', sa.String(length=255), nullable=True),
    sa.Column('Sequencing_facility', sa.String(length=255), nullable=True),
    sa.Column('Expedition_lead', sa.String(length=255), nullable=True),
    sa.Column('Collaborators', sa.String(length=255), nullable=True),
    sa.Column('Primer_set_1', sa.String(length=255), nullable=True),
    sa.Column('Primer_set_2', sa.String(length=255), nullable=True),
    sa.Column('Extraction_method', sa.String(length=255), nullable=True),
    sa.Column('Multiple_sequencing_runs', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['buckets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sequencing_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequencingUploadId', sa.Integer(), nullable=True),
    sa.Column('SampleID', sa.String(length=255), nullable=True),
    sa.Column('SequencerID', sa.String(length=255), nullable=True),
    sa.Column('Site_name', sa.String(length=255), nullable=True),
    sa.Column('Latitude', sa.String(length=255), nullable=True),
    sa.Column('Longitude', sa.String(length=255), nullable=True),
    sa.Column('Vegetation', sa.String(length=255), nullable=True),
    sa.Column('Land_use', sa.String(length=255), nullable=True),
    sa.Column('Agricultural_land', sa.String(length=255), nullable=True),
    sa.Column('Treatments', sa.String(length=255), nullable=True),
    sa.Column('Ecosystem', sa.String(length=255), nullable=True),
    sa.Column('Grid_Size', sa.String(length=255), nullable=True),
    sa.Column('Soil_depth', sa.String(length=255), nullable=True),
    sa.Column('Transport_refrigeration', sa.String(length=255), nullable=True),
    sa.Column('Drying', sa.String(length=255), nullable=True),
    sa.Column('Date_collected', sa.String(length=255), nullable=True),
    sa.Column('DNA_concentration_ng_ul', sa.String(length=255), nullable=True),
    sa.Column('DNA_conc_instrument', sa.String(length=255), nullable=True),
    sa.Column('Elevation', sa.String(length=255), nullable=True),
    sa.Column('Sample_or_Control', sa.String(length=255), nullable=True),
    sa.Column('SequencingRun', sa.String(length=255), nullable=True),
    sa.Column('Notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['sequencingUploadId'], ['sequencing_uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sequencing_samples')
    op.drop_table('sequencing_uploads')
    # ### end Alembic commands ###
