"""

Revision ID: 084aaeb3501f
Revises: 0fecb9258f75
Create Date: 2026-07-01 06:38:58.059682

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "084aaeb3501f"
down_revision: Union[str, None] = "0fecb9258f75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mobile_app_staging_photos",
        sa.Column("content_hash", sa.String(length=32), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mobile_app_staging_photos", "content_hash")
    # ### end Alembic commands ###
