"""Add field for fastqc celery process id

Revision ID: 110d33875ca8
Revises: 40f75ab07ff4
Create Date: 2024-01-03 08:43:31.734251

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "110d33875ca8"
down_revision: Union[str, None] = "40f75ab07ff4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "uploads", sa.Column("fastqc_process_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_uploads_fastqc_process_id"),
        "uploads",
        ["fastqc_process_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_uploads_fastqc_process_id"), table_name="uploads")
    op.drop_column("uploads", "fastqc_process_id")
    # ### end Alembic commands ###
