"""

Revision ID: 141b0c54705d
Revises: a6a93516ce0a
Create Date: 2026-03-16 09:49:01.260589

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "141b0c54705d"
down_revision: Union[str, None] = "a6a93516ce0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meta_projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("results_folder", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "meta_project_uploads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("meta_project_id", sa.Integer(), nullable=False),
        sa.Column("sequencing_upload_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meta_project_id"], ["meta_projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["sequencing_upload_id"],
            ["sequencing_uploads.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "sequencing_analysis",
        sa.Column("metaProjectId", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        "fk_sequencing_analysis_meta_project",
        "sequencing_analysis",
        "meta_projects",
        ["metaProjectId"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_sequencing_analysis_meta_project",
        "sequencing_analysis",
        type_="foreignkey",
    )
    op.drop_column("sequencing_analysis", "metaProjectId")
    op.drop_table("meta_project_uploads")
    op.drop_table("meta_projects")
    # ### end Alembic commands ###
