"""Delete fields for gz_sent_to_bucket

Revision ID: 18210c838fb9
Revises: d69dd4859815
Create Date: 2024-02-08 09:11:54.633220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '18210c838fb9'
down_revision: Union[str, None] = 'd69dd4859815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'gz_sent_to_bucket_progress')
    op.drop_column('uploads', 'gz_sent_to_bucket')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('gz_sent_to_bucket', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('uploads', sa.Column('gz_sent_to_bucket_progress', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
