"""Add field for approved users

Revision ID: 2e43da21f4cd
Revises: 48bba3f7a871
Create Date: 2024-01-22 13:06:50.489758

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2e43da21f4cd"
down_revision: Union[str, None] = "48bba3f7a871"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("approved", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "approved")
    # ### end Alembic commands ###
