"""Add progress report to archive creation

Revision ID: 2ebf9ccc05cd
Revises: 6450ad592333
Create Date: 2024-04-16 09:19:37.612774

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2ebf9ccc05cd"
down_revision: Union[str, None] = "6450ad592333"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "buckets",
        sa.Column(
            "archive_file_creation_progress", sa.Integer(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("buckets", "archive_file_creation_progress")
    # ### end Alembic commands ###
