"""Add ResolveEcoregion and BaileysEcoregion fields to samples

Revision ID: 2f792ce7de57
Revises: 6bc9666cd137
Create Date: 2024-11-26 08:24:04.826212

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2f792ce7de57"
down_revision: Union[str, None] = "6bc9666cd137"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequencing_samples",
        sa.Column("ResolveEcoregion", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "sequencing_samples",
        sa.Column("BaileysEcoregion", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequencing_samples", "BaileysEcoregion")
    op.drop_column("sequencing_samples", "ResolveEcoregion")
    # ### end Alembic commands ###
