"""

Revision ID: 31eddd5b2de7
Revises: 85128afa6aae
Create Date: 2026-07-08 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31eddd5b2de7"
down_revision: Union[str, None] = "85128afa6aae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sequencing_sample_photos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sequencing_sample_id", sa.Integer(), nullable=False),
        sa.Column("source_mobile_photo_id", sa.Integer(), nullable=True),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("content_hash", sa.String(length=32), nullable=True),
        sa.Column("coords_extracted", sa.Boolean(), nullable=True),
        sa.Column("received_at", sa.DateTime(), nullable=True),
        sa.Column("transferred_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sequencing_sample_id"],
            ["sequencing_samples.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_mobile_photo_id"],
            ["mobile_app_staging_photos.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_ssp_sequencing_sample_id",
        "sequencing_sample_photos",
        ["sequencing_sample_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_ssp_sequencing_sample_id",
        table_name="sequencing_sample_photos",
    )
    op.drop_table("sequencing_sample_photos")
    # ### end Alembic commands ###
