"""Added column for reviewed_by_admin

Revision ID: 37c0420b998d
Revises: f56c186676a9
Create Date: 2024-05-09 06:42:18.547085

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "37c0420b998d"
down_revision: Union[str, None] = "f56c186676a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "uploads", sa.Column("reviewed_by_admin", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("uploads", "reviewed_by_admin")
    # ### end Alembic commands ###
