"""Add analysis parameters

Revision ID: 3d4df13fb19a
Revises: 2f792ce7de57
Create Date: 2024-11-27 08:57:26.458151

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "3d4df13fb19a"
down_revision: Union[str, None] = "2f792ce7de57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequencing_analysis",
        sa.Column("parameters", mysql.JSON(none_as_null=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequencing_analysis", "parameters")
    # ### end Alembic commands ###
