"""Change id field of users table to accomodate google ids second try

Revision ID: 3e00792d90db
Revises: a8ab8a61a18a
Create Date: 2023-12-14 14:56:27.296726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3e00792d90db'
down_revision: Union[str, None] = 'a8ab8a61a18a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.String(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False)
    # ### end Alembic commands ###
