"""Drop reports status fields from uploads table

Revision ID: 40df2181a6bb
Revises: 93d024d36b5f
Create Date: 2025-02-10 08:28:28.724321

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "40df2181a6bb"
down_revision: Union[str, None] = "93d024d36b5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequencing_uploads", "region_1_rscripts_report_status")
    op.drop_column("sequencing_uploads", "region_2_rscripts_report_started_at")
    op.drop_column("sequencing_uploads", "region_1_rscripts_report_result")
    op.drop_column("sequencing_uploads", "region_2_rscripts_report_task_id")
    op.drop_column("sequencing_uploads", "region_1_rscripts_report_task_id")
    op.drop_column("sequencing_uploads", "region_1_rscripts_report_started_at")
    op.drop_column("sequencing_uploads", "region_2_rscripts_report_result")
    op.drop_column("sequencing_uploads", "region_2_rscripts_report_status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_2_rscripts_report_status",
            mysql.VARCHAR(length=255),
            nullable=True,
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_2_rscripts_report_result",
            mysql.TEXT(charset="utf8"),
            nullable=True,
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_1_rscripts_report_started_at",
            mysql.DATETIME(),
            nullable=True,
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_1_rscripts_report_task_id",
            mysql.VARCHAR(length=255),
            nullable=True,
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_2_rscripts_report_task_id",
            mysql.VARCHAR(length=255),
            nullable=True,
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_1_rscripts_report_result",
            mysql.TEXT(charset="utf8"),
            nullable=True,
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_2_rscripts_report_started_at",
            mysql.DATETIME(),
            nullable=True,
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_1_rscripts_report_status",
            mysql.VARCHAR(length=255),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
