"""Add boolean for fastqc run

Revision ID: 40f75ab07ff4
Revises: 7f1941de0aa4
Create Date: 2023-12-21 10:25:40.457725

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "40f75ab07ff4"
down_revision: Union[str, None] = "7f1941de0aa4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("uploads", sa.Column("fastqc_run", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("uploads", "fastqc_run")
    # ### end Alembic commands ###
