"""Create Resolve ecoregions table

Revision ID: 4120dd0380c6
Revises: 7e08cc014e8e
Create Date: 2025-02-24 08:17:04.113842

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4120dd0380c6"
down_revision: Union[str, None] = "7e08cc014e8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resolve_ecoregions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("FID", sa.Integer(), nullable=False),
        sa.Column("OBJECTID", sa.Integer(), nullable=False),
        sa.Column("ecoregion_name", sa.String(length=255), nullable=True),
        sa.Column("biome_number", sa.Integer(), nullable=True),
        sa.Column("biome_name", sa.String(length=255), nullable=True),
        sa.Column("realm_name", sa.String(length=255), nullable=True),
        sa.Column("ecoregion_biome", sa.String(length=255), nullable=True),
        sa.Column("nature_needs_half_number", sa.Integer(), nullable=True),
        sa.Column("ecoregion_unique_id", sa.Integer(), nullable=True),
        sa.Column("shape_leng", sa.Float(), nullable=True),
        sa.Column(
            "nature_needs_half_description",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column("color", sa.String(length=50), nullable=True),
        sa.Column("biome_color", sa.String(length=50), nullable=True),
        sa.Column(
            "nature_needs_half_color", sa.String(length=50), nullable=True
        ),
        sa.Column("license", sa.String(length=255), nullable=True),
        sa.Column("shape_area", sa.Float(), nullable=True),
        sa.Column("shape_length", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resolve_ecoregions")
    # ### end Alembic commands ###
