"""Add flag for files_uploading_confirmed to sequencing_uploads table

Revision ID: 435c319f7b31
Revises: cc96e9918aa7
Create Date: 2024-08-26 12:50:53.034459

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "435c319f7b31"
down_revision: Union[str, None] = "cc96e9918aa7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequencing_uploads",
        sa.Column("files_uploading_confirmed", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequencing_uploads", "files_uploading_confirmed")
    # ### end Alembic commands ###
