"""Field to keep track of how many fastqc files were done

Revision ID: 48bba3f7a871
Revises: ff0e56636e1f
Create Date: 2024-01-18 15:37:40.691718

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "48bba3f7a871"
down_revision: Union[str, None] = "ff0e56636e1f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "uploads",
        sa.Column("fastqc_files_progress", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("uploads", "fastqc_files_progress")
    # ### end Alembic commands ###
