"""Remove non needed fields for bucket archive creation

Revision ID: 493bbb939e03
Revises: d8f47c8747eb
Create Date: 2025-04-03 14:10:43.353946

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "493bbb939e03"
down_revision: Union[str, None] = "d8f47c8747eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("buckets", "archive_file")
    op.drop_column("buckets", "archive_file_creation_progress")
    op.drop_column("buckets", "archive_file_created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "buckets",
        sa.Column("archive_file_created_at", mysql.DATETIME(), nullable=True),
    )
    op.add_column(
        "buckets",
        sa.Column(
            "archive_file_creation_progress",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "buckets",
        sa.Column("archive_file", mysql.VARCHAR(length=255), nullable=True),
    )
    # ### end Alembic commands ###
