"""Add table for external samples

Revision ID: 4c598b1536be
Revises: 4120dd0380c6
Create Date: 2025-02-24 13:06:13.151341

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4c598b1536be"
down_revision: Union[str, None] = "4120dd0380c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "external_sampling",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sample_id", sa.String(length=255), nullable=True),
        sa.Column("dna_region", sa.String(length=3), nullable=True),
        sa.Column("longitude", sa.String(length=255), nullable=True),
        sa.Column("latitude", sa.String(length=255), nullable=True),
        sa.Column("resolve_ecoregion_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["resolve_ecoregion_id"],
            ["resolve_ecoregions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_dna_region", "external_sampling", ["dna_region"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_dna_region", table_name="external_sampling")
    op.drop_table("external_sampling")
    # ### end Alembic commands ###
