"""Fields for tracking lotus2 reports generation

Revision ID: 4dfbc6e3af62
Revises: 89ecfd9d28e7
Create Date: 2024-09-26 06:21:55.785277

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4dfbc6e3af62"
down_revision: Union[str, None] = "89ecfd9d28e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_1_lotus2_report_task_id",
            sa.String(length=255),
            nullable=True,
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_1_lotus2_report_started_at", sa.DateTime(), nullable=True
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_1_lotus2_report_status",
            sa.String(length=255),
            nullable=True,
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column("region_1_lotus2_report_result", sa.Text(), nullable=True),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_2_lotus2_report_task_id",
            sa.String(length=255),
            nullable=True,
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_2_lotus2_report_started_at", sa.DateTime(), nullable=True
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_2_lotus2_report_status",
            sa.String(length=255),
            nullable=True,
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column("region_2_lotus2_report_result", sa.Text(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequencing_uploads", "region_2_lotus2_report_result")
    op.drop_column("sequencing_uploads", "region_2_lotus2_report_status")
    op.drop_column("sequencing_uploads", "region_2_lotus2_report_started_at")
    op.drop_column("sequencing_uploads", "region_2_lotus2_report_task_id")
    op.drop_column("sequencing_uploads", "region_1_lotus2_report_result")
    op.drop_column("sequencing_uploads", "region_1_lotus2_report_status")
    op.drop_column("sequencing_uploads", "region_1_lotus2_report_started_at")
    op.drop_column("sequencing_uploads", "region_1_lotus2_report_task_id")
    # ### end Alembic commands ###
