"""Add field for IndeginousPartnership to samples table

Revision ID: 5155133ba4e4
Revises: 3d4df13fb19a
Create Date: 2024-12-03 13:47:52.585691

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5155133ba4e4"
down_revision: Union[str, None] = "3d4df13fb19a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequencing_samples",
        sa.Column("IndigenousPartnership", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequencing_samples", "IndigenousPartnership")
    # ### end Alembic commands ###
