"""

Revision ID: 534ebd65812c
Revises: 888a660c68e0
Create Date: 2026-07-06 12:34:03.851669

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "534ebd65812c"
down_revision: Union[str, None] = "888a660c68e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meta_projects",
        sa.Column("share_url", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "meta_projects",
        sa.Column("share_sync_completed", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meta_projects", "share_sync_completed")
    op.drop_column("meta_projects", "share_url")
    # ### end Alembic commands ###
