"""

Revision ID: 58855b6043b1
Revises: a373ae470bb5
Create Date: 2026-08-12 07:49:00.292827

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "58855b6043b1"
down_revision: Union[str, None] = "a373ae470bb5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mobile_app_staging_samples",
        sa.Column("extra_data", sa.JSON(none_as_null=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mobile_app_staging_samples", "extra_data")
    # ### end Alembic commands ###
