"""Seperate primer sets to forward and reverse

Revision ID: 5a179c7c8604
Revises: 8194d6881623
Create Date: 2024-08-28 11:00:58.610215

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5a179c7c8604"
down_revision: Union[str, None] = "8194d6881623"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_1_forward_primer", sa.String(length=255), nullable=True
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_1_reverse_primer", sa.String(length=255), nullable=True
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_2_forward_primer", sa.String(length=255), nullable=True
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_2_reverse_primer", sa.String(length=255), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequencing_uploads", "region_2_forward_primer")
    op.drop_column("sequencing_uploads", "region_1_reverse_primer")
    op.drop_column("sequencing_uploads", "region_1_forward_primer")
    op.drop_column("sequencing_uploads", "region_2_reverse_primer")
    # ### end Alembic commands ###
