"""Add analysis field to OTUs

Revision ID: 5f782f8dda38
Revises: a2c679f0145e
Create Date: 2025-01-20 12:37:12.882364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5f782f8dda38'
down_revision: Union[str, None] = 'a2c679f0145e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otu', sa.Column('sequencing_analysis_id', sa.Integer(), nullable=False))
    op.alter_column('otu', 'abundance',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'otu', 'sequencing_analysis', ['sequencing_analysis_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'otu', type_='foreignkey')
    op.alter_column('otu', 'abundance',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.drop_column('otu', 'sequencing_analysis_id')
    # ### end Alembic commands ###
