"""Add field for extra sample data

Revision ID: 632c06b97178
Revises: d5abe5bcee9a
Create Date: 2024-09-04 08:53:24.020215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '632c06b97178'
down_revision: Union[str, None] = 'd5abe5bcee9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sequencing_samples', sa.Column('extracolumns_json', mysql.JSON(none_as_null=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sequencing_samples', 'extracolumns_json')
    # ### end Alembic commands ###
