"""Add association table for buckets of user

Revision ID: 6450ad592333
Revises: a5e26b8e1ce5
Create Date: 2024-04-16 07:40:14.874226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6450ad592333'
down_revision: Union[str, None] = 'a5e26b8e1ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buckets',
    sa.Column('id', sa.String(length=250), nullable=False),
    sa.Column('archive_file', sa.String(length=255), nullable=True),
    sa.Column('archive_file_created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_buckets',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('bucket_id', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['bucket_id'], ['buckets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_column('users', 'buckets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('buckets', mysql.JSON(), nullable=True))
    op.drop_table('user_buckets')
    op.drop_table('buckets')
    # ### end Alembic commands ###
