"""Change user_id field to match google id

Revision ID: 67f6e256a101
Revises: bf0640fbee96
Create Date: 2023-12-18 08:22:24.757327

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "67f6e256a101"
down_revision: Union[str, None] = "bf0640fbee96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "uploads",
        "user_id",
        existing_type=mysql.INTEGER(display_width=11),
        type_=sa.String(length=36),
        nullable=True,
    )
    op.create_index(
        op.f("ix_uploads_user_id"), "uploads", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_uploads_user_id"), table_name="uploads")
    op.alter_column(
        "uploads",
        "user_id",
        existing_type=sa.String(length=36),
        type_=mysql.INTEGER(display_width=11),
        nullable=False,
    )
    # ### end Alembic commands ###
