"""Add field for tracking progress of gz raw file to bucket

Revision ID: 69a0bd55117a
Revises: 93a2441c0773
Create Date: 2024-01-08 12:08:52.631644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a0bd55117a'
down_revision: Union[str, None] = '93a2441c0773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('gz_sent_to_bucket_progress', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'gz_sent_to_bucket_progress')
    # ### end Alembic commands ###
