"""Add number of sequencing regions to analyse

Revision ID: 69d49ce491bd
Revises: 782a3d7f4e66
Create Date: 2024-07-17 11:21:48.270210

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "69d49ce491bd"
down_revision: Union[str, None] = "782a3d7f4e66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequencing_uploads",
        sa.Column("Sequencing_regions_number", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequencing_uploads", "Sequencing_regions_number")
    # ### end Alembic commands ###
