"""Rscript reports status fields

Revision ID: 6acfbb55ed5b
Revises: d4f5bae7da0d
Create Date: 2024-11-06 09:25:58.010324

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6acfbb55ed5b"
down_revision: Union[str, None] = "d4f5bae7da0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_1_rscripts_report_task_id",
            sa.String(length=255),
            nullable=True,
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_1_rscripts_report_started_at", sa.DateTime(), nullable=True
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_1_rscripts_report_status",
            sa.String(length=255),
            nullable=True,
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_1_rscripts_report_result",
            sa.Text(collation="utf8_general_ci"),
            nullable=True,
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_2_rscripts_report_task_id",
            sa.String(length=255),
            nullable=True,
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_2_rscripts_report_started_at", sa.DateTime(), nullable=True
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_2_rscripts_report_status",
            sa.String(length=255),
            nullable=True,
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_2_rscripts_report_result",
            sa.Text(collation="utf8_general_ci"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequencing_uploads", "region_2_rscripts_report_result")
    op.drop_column("sequencing_uploads", "region_2_rscripts_report_status")
    op.drop_column("sequencing_uploads", "region_2_rscripts_report_started_at")
    op.drop_column("sequencing_uploads", "region_2_rscripts_report_task_id")
    op.drop_column("sequencing_uploads", "region_1_rscripts_report_result")
    op.drop_column("sequencing_uploads", "region_1_rscripts_report_status")
    op.drop_column("sequencing_uploads", "region_1_rscripts_report_started_at")
    op.drop_column("sequencing_uploads", "region_1_rscripts_report_task_id")
    # ### end Alembic commands ###
