"""Move DNA_conc_instrument to common project data

Revision ID: 6f8b52b20365
Revises: d87943516b46
Create Date: 2024-07-22 11:32:17.744698

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "6f8b52b20365"
down_revision: Union[str, None] = "d87943516b46"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequencing_samples", "Treatments")
    op.drop_column("sequencing_samples", "DNA_conc_instrument")
    op.add_column(
        "sequencing_uploads",
        sa.Column("DNA_conc_instrument", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequencing_uploads", "DNA_conc_instrument")
    op.add_column(
        "sequencing_samples",
        sa.Column(
            "DNA_conc_instrument", mysql.VARCHAR(length=255), nullable=True
        ),
    )
    op.add_column(
        "sequencing_samples",
        sa.Column("Treatments", mysql.VARCHAR(length=255), nullable=True),
    )
    # ### end Alembic commands ###
