"""Add ecm flag to OTU table

Revision ID: 746b0ea27de0
Revises: 40df2181a6bb
Create Date: 2025-02-17 08:36:37.559403

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "746b0ea27de0"
down_revision: Union[str, None] = "40df2181a6bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "otu",
        sa.Column(
            "ecm_flag", sa.Boolean(), server_default="0", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("otu", "ecm_flag")
    # ### end Alembic commands ###
