"""Add tables for sequencerID and uploaded files

Revision ID: 782a3d7f4e66
Revises: edd64ee8fd53
Create Date: 2024-07-17 07:27:55.748448

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "782a3d7f4e66"
down_revision: Union[str, None] = "edd64ee8fd53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sequencing_sequencer_ids",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sequencingSampleId", sa.Integer(), nullable=True),
        sa.Column("SequencerID", sa.String(length=255), nullable=True),
        sa.Column("Region", sa.String(length=25), nullable=True),
        sa.ForeignKeyConstraint(
            ["sequencingSampleId"],
            ["sequencing_samples.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sequencing_files_uploaded",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sequencerId", sa.Integer(), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("new_name", sa.String(length=25), nullable=True),
        sa.ForeignKeyConstraint(
            ["sequencerId"],
            ["sequencing_sequencer_ids.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("sequencing_samples", "SequencerID")
    op.drop_column("sequencing_samples", "Region")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequencing_samples",
        sa.Column("Region", mysql.VARCHAR(length=25), nullable=True),
    )
    op.add_column(
        "sequencing_samples",
        sa.Column("SequencerID", mysql.VARCHAR(length=255), nullable=True),
    )
    op.drop_table("sequencing_files_uploaded")
    op.drop_table("sequencing_sequencer_ids")
    # ### end Alembic commands ###
