"""Add indexes for ecm_flag

Revision ID: 7e08cc014e8e
Revises: 746b0ea27de0
Create Date: 2025-02-17 09:09:52.912987

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e08cc014e8e"
down_revision: Union[str, None] = "746b0ea27de0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_ecm_analysis",
        "otu",
        ["ecm_flag", "sequencing_analysis_id"],
        unique=False,
    )
    op.create_index("idx_ecm_flag", "otu", ["ecm_flag"], unique=False)
    op.create_index(
        "idx_ecm_sample", "otu", ["ecm_flag", "sample_id"], unique=False
    )
    op.create_index(
        "idx_ecm_taxonomy", "otu", ["ecm_flag", "taxonomy_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_ecm_taxonomy", table_name="otu")
    op.drop_index("idx_ecm_sample", table_name="otu")
    op.drop_index("idx_ecm_flag", table_name="otu")
    op.drop_index("idx_ecm_analysis", table_name="otu")
    # ### end Alembic commands ###
