"""Add json field for keeping track of files

Revision ID: 7f1941de0aa4
Revises: 3a6e3691a8c2
Create Date: 2023-12-21 09:10:32.341858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7f1941de0aa4'
down_revision: Union[str, None] = '3a6e3691a8c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('files_json', mysql.JSON(none_as_null=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'files_json')
    # ### end Alembic commands ###
