"""

Revision ID: 85128afa6aae
Revises: 534ebd65812c
Create Date: 2026-07-08 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "85128afa6aae"
down_revision: Union[str, None] = "534ebd65812c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mobile_app_staging_samples",
        sa.Column("transferred_to_upload_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "mobile_app_staging_samples",
        sa.Column("transferred_at", sa.DateTime(), nullable=True),
    )
    op.create_index(
        "idx_mss_transferred_to_upload_id",
        "mobile_app_staging_samples",
        ["transferred_to_upload_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_mss_transferred_to_upload_id",
        "mobile_app_staging_samples",
        "sequencing_uploads",
        ["transferred_to_upload_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_mss_transferred_to_upload_id",
        "mobile_app_staging_samples",
        type_="foreignkey",
    )
    op.drop_index(
        "idx_mss_transferred_to_upload_id",
        table_name="mobile_app_staging_samples",
    )
    op.drop_column("mobile_app_staging_samples", "transferred_at")
    op.drop_column("mobile_app_staging_samples", "transferred_to_upload_id")
    # ### end Alembic commands ###
