"""

Revision ID: 888a660c68e0
Revises: ec3d1ec91228
Create Date: 2026-07-01 09:54:28.195949

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "888a660c68e0"
down_revision: Union[str, None] = "ec3d1ec91228"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mobile_app_staging_photos",
        sa.Column("coords_extracted", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mobile_app_staging_photos", "coords_extracted")
    # ### end Alembic commands ###
