"""Add field for fastqc sent to bucket

Revision ID: 93a2441c0773
Revises: 911ee5c29727
Create Date: 2024-01-08 09:36:55.508469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '93a2441c0773'
down_revision: Union[str, None] = '911ee5c29727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunk_storage')
    op.add_column('uploads', sa.Column('fastqc_sent_to_bucket', sa.Boolean(), nullable=True))
    op.drop_column('uploads', 'gz_nr_chunks_uploaded')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('gz_nr_chunks_uploaded', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('uploads', 'fastqc_sent_to_bucket')
    op.create_table('chunk_storage',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('process_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('chunk_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['uploads.id'], name='chunk_storage_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
