"""Add field for fastqc sent to bucket

Revision ID: 93a2441c0773
Revises: 911ee5c29727
Create Date: 2024-01-08 09:36:55.508469

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "93a2441c0773"
down_revision: Union[str, None] = "911ee5c29727"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "uploads",
        sa.Column("fastqc_sent_to_bucket", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("uploads", "fastqc_sent_to_bucket")
    # ### end Alembic commands ###
