"""

Revision ID: 9921085efd3c
Revises: 31eddd5b2de7
Create Date: 2026-07-14 06:54:44.420496

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9921085efd3c"
down_revision: Union[str, None] = "31eddd5b2de7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "indigenous_territory_status", sa.String(length=255), nullable=True
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column("territory_name", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequencing_uploads", "territory_name")
    op.drop_column("sequencing_uploads", "indigenous_territory_status")
    # ### end Alembic commands ###
