"""Change field grid_size to be 24 characters long

Revision ID: 9ec3d957c178
Revises: e4f5a6b7c8d9
Create Date: 2026-05-28 13:47:21.245675

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "9ec3d957c178"
down_revision: Union[str, None] = "e4f5a6b7c8d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_msph_project_id", table_name="mobile_app_staging_photos"
    )
    op.alter_column(
        "mobile_app_staging_samples",
        "grid_size",
        existing_type=mysql.VARCHAR(length=20),
        type_=sa.String(length=24),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "mobile_app_staging_samples",
        "grid_size",
        existing_type=sa.String(length=24),
        type_=mysql.VARCHAR(length=20),
        existing_nullable=True,
    )
    op.create_index(
        "idx_msph_project_id",
        "mobile_app_staging_photos",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###
