"""Add field for bucket access to user

Revision ID: a5e26b8e1ce5
Revises: 68a8ad337a77
Create Date: 2024-04-15 07:19:26.780910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a5e26b8e1ce5'
down_revision: Union[str, None] = '68a8ad337a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('buckets', mysql.JSON(none_as_null=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'buckets')
    # ### end Alembic commands ###
