"""Change id field of users table to accomodate google ids

Revision ID: a8ab8a61a18a
Revises: 538d8602afd3
Create Date: 2023-12-14 14:54:18.994506

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "a8ab8a61a18a"
down_revision: Union[str, None] = "538d8602afd3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "id",
        existing_type=mysql.INTEGER(display_width=11),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "id",
        existing_type=sa.BigInteger(),
        type_=mysql.INTEGER(display_width=11),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
