"""Create fields for upload of gz file

Revision ID: ac29df4f440f
Revises: 67f6e256a101
Create Date: 2023-12-18 09:11:14.821554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac29df4f440f'
down_revision: Union[str, None] = '67f6e256a101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('gz_uploaded', sa.Boolean(), nullable=True))
    op.add_column('uploads', sa.Column('gz_filename', sa.String(length=255), nullable=True))
    op.add_column('uploads', sa.Column('gz_sent_to_bucket', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'gz_sent_to_bucket')
    op.drop_column('uploads', 'gz_filename')
    op.drop_column('uploads', 'gz_uploaded')
    # ### end Alembic commands ###
