"""add_exclude_from_global_mapping_to_sequencing_uploads

Revision ID: ac9962d3f325
Revises: 229bfb353632
Create Date: 2026-09-03 10:46:02.269317

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ac9962d3f325"
down_revision: Union[str, None] = "229bfb353632"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequencing_uploads",
        sa.Column("exclude_from_global_mapping", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequencing_uploads", "exclude_from_global_mapping")
    # ### end Alembic commands ###
