"""Add boolean for unzipping files

Revision ID: b94ce0a40898
Revises: ac29df4f440f
Create Date: 2023-12-19 08:40:16.713870

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b94ce0a40898"
down_revision: Union[str, None] = "ac29df4f440f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "uploads", sa.Column("gz_unziped", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("uploads", "gz_unziped")
    # ### end Alembic commands ###
