"""Drop lotus2 fields in sequencing_uploads table

Revision ID: bbd5fb21ff61
Revises: 130d89177a44
Create Date: 2024-11-11 11:48:34.594036

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "bbd5fb21ff61"
down_revision: Union[str, None] = "130d89177a44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequencing_uploads", "region_2_lotus2_report_result")
    op.drop_column("sequencing_uploads", "region_1_lotus2_report_status")
    op.drop_column("sequencing_uploads", "region_2_lotus2_report_task_id")
    op.drop_column("sequencing_uploads", "region_2_lotus2_report_started_at")
    op.drop_column("sequencing_uploads", "region_2_lotus2_report_status")
    op.drop_column("sequencing_uploads", "region_1_lotus2_report_started_at")
    op.drop_column("sequencing_uploads", "region_1_lotus2_report_result")
    op.drop_column("sequencing_uploads", "region_1_lotus2_report_task_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_1_lotus2_report_task_id",
            mysql.VARCHAR(length=255),
            nullable=True,
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_1_lotus2_report_result",
            mysql.TEXT(charset="utf8mb4", collation="utf8mb4_unicode_ci"),
            nullable=True,
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_1_lotus2_report_started_at",
            mysql.DATETIME(),
            nullable=True,
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_2_lotus2_report_status",
            mysql.VARCHAR(length=255),
            nullable=True,
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_2_lotus2_report_started_at",
            mysql.DATETIME(),
            nullable=True,
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_2_lotus2_report_task_id",
            mysql.VARCHAR(length=255),
            nullable=True,
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_1_lotus2_report_status",
            mysql.VARCHAR(length=255),
            nullable=True,
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "region_2_lotus2_report_result",
            mysql.TEXT(charset="utf8mb4", collation="utf8mb4_unicode_ci"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
