"""Tables for v2 scripps upload

Revision ID: be094b7d616e
Revises: 4dfbc6e3af62
Create Date: 2024-10-02 09:38:49.085676

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "be094b7d616e"
down_revision: Union[str, None] = "4dfbc6e3af62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sequencing_company_uploads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("uploads_folder", sa.String(length=20), nullable=True),
        sa.Column("csv_filename", sa.String(length=255), nullable=True),
        sa.Column("tar_filename", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sequencing_company_input",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sequencingCompanyUploadId", sa.Integer(), nullable=True),
        sa.Column("sample_number", sa.String(length=255), nullable=True),
        sa.Column("sample_id", sa.String(length=255), nullable=True),
        sa.Column("sequencer_id", sa.String(length=255), nullable=True),
        sa.Column("sequencing_provider", sa.String(length=255), nullable=True),
        sa.Column("project", sa.String(length=50), nullable=True),
        sa.Column("region", sa.String(length=50), nullable=True),
        sa.Column("index_1", sa.String(length=50), nullable=True),
        sa.Column("barcode_2", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["sequencingCompanyUploadId"],
            ["sequencing_company_uploads.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sequencing_company_input")
    op.drop_table("sequencing_company_uploads")
    # ### end Alembic commands ###
