"""Add goodgrands_slug field to users table

Revision ID: bf5b2663a7f5
Revises: 632c06b97178
Create Date: 2024-09-21 08:53:45.822037

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bf5b2663a7f5"
down_revision: Union[str, None] = "632c06b97178"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("goodgrands_slug", sa.String(length=50), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "goodgrands_slug")
    # ### end Alembic commands ###
