"""Make lookup table for analysis

Revision ID: c1283df0e46a
Revises: 6acfbb55ed5b
Create Date: 2024-11-11 08:33:07.382211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c1283df0e46a'
down_revision: Union[str, None] = '6acfbb55ed5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequencing_analysis_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('parameters', mysql.JSON(none_as_null=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sequencing_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequencingUploadId', sa.Integer(), nullable=True),
    sa.Column('sequencingAnalysisTypeId', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('result', sa.Text(collation="utf8_general_ci"), nullable=True),
    sa.ForeignKeyConstraint(['sequencingAnalysisTypeId'], ['sequencing_analysis_types.id'], ),
    sa.ForeignKeyConstraint(['sequencingUploadId'], ['sequencing_uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sequencing_analysis')
    op.drop_table('sequencing_analysis_types')
    # ### end Alembic commands ###
