"""

Revision ID: c4976f64b5f3
Revises: c07bdb489b9c
Create Date: 2026-07-14 08:35:34.467331

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c4976f64b5f3"
down_revision: Union[str, None] = "c07bdb489b9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequencing_uploads",
        sa.Column("belongs_to_community", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column("permits_confirmed", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column("collaboration_type", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "community_contact_info", sa.String(length=255), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequencing_uploads", "community_contact_info")
    op.drop_column("sequencing_uploads", "collaboration_type")
    op.drop_column("sequencing_uploads", "permits_confirmed")
    op.drop_column("sequencing_uploads", "belongs_to_community")
    # ### end Alembic commands ###
