"""Add field gz_unziped_progress to uploads table

Revision ID: c6545a0647e6
Revises: 69a0bd55117a
Create Date: 2024-01-09 13:11:24.130712

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c6545a0647e6"
down_revision: Union[str, None] = "69a0bd55117a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "uploads", sa.Column("gz_unziped_progress", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("uploads", "gz_unziped_progress")
    # ### end Alembic commands ###
