"""Raise size of new_name field

Revision ID: cc96e9918aa7
Revises: 252743430cc4
Create Date: 2024-08-26 09:27:31.208212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cc96e9918aa7'
down_revision: Union[str, None] = '252743430cc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sequencing_files_uploaded', 'new_name',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sequencing_files_uploaded', 'new_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=True)
    # ### end Alembic commands ###
