"""Add field for lotus2_command

Revision ID: cf0c36f9a9af
Revises: 63b8eb6379c7
Create Date: 2025-08-05 10:08:58.371876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cf0c36f9a9af'
down_revision: Union[str, None] = '63b8eb6379c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sequencing_analysis', sa.Column('lotus2_command', mysql.MEDIUMTEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sequencing_analysis', 'lotus2_command')
    # ### end Alembic commands ###
