"""Fields for adapter primers count

Revision ID: d40180d39f80
Revises: f14349630eca
Create Date: 2025-06-17 12:52:14.156171

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d40180d39f80"
down_revision: Union[str, None] = "f14349630eca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequencing_sequencer_ids",
        sa.Column("fwd_read_fwd_adap", sa.Integer(), nullable=True),
    )
    op.add_column(
        "sequencing_sequencer_ids",
        sa.Column("rev_read_rev_adap", sa.Integer(), nullable=True),
    )
    op.add_column(
        "sequencing_sequencer_ids",
        sa.Column("fwd_rev_adap", sa.Integer(), nullable=True),
    )
    op.add_column(
        "sequencing_sequencer_ids",
        sa.Column("fwd_rev_mrg_adap", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequencing_sequencer_ids", "fwd_rev_mrg_adap")
    op.drop_column("sequencing_sequencer_ids", "fwd_rev_adap")
    op.drop_column("sequencing_sequencer_ids", "rev_read_rev_adap")
    op.drop_column("sequencing_sequencer_ids", "fwd_read_fwd_adap")
    # ### end Alembic commands ###
