"""Share url fields in uploads table

Revision ID: d8f47c8747eb
Revises: b4fbb84b5b4e
Create Date: 2025-03-26 08:07:57.175815

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d8f47c8747eb"
down_revision: Union[str, None] = "b4fbb84b5b4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequencing_uploads",
        sa.Column("share_url", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column("share_sync_completed", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequencing_uploads", "share_sync_completed")
    op.drop_column("sequencing_uploads", "share_url")
    # ### end Alembic commands ###
