"""Add fields for lotus2 reporting tracking

Revision ID: dfea07987bb2
Revises: 89ecfd9d28e7
Create Date: 2024-09-25 13:19:12.980877

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dfea07987bb2"
down_revision: Union[str, None] = "89ecfd9d28e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequencing_uploads",
        sa.Column("lotus2_report_task_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column("lotus2_report_started_at", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column(
            "lotus2_report_status", sa.String(length=255), nullable=True
        ),
    )
    op.add_column(
        "sequencing_uploads",
        sa.Column("lotus2_report_result", sa.Text(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequencing_uploads", "lotus2_report_result")
    op.drop_column("sequencing_uploads", "lotus2_report_status")
    op.drop_column("sequencing_uploads", "lotus2_report_started_at")
    op.drop_column("sequencing_uploads", "lotus2_report_task_id")
    # ### end Alembic commands ###
