"""Correct field type for celery task_id

Revision ID: e7dd1f869034
Revises: dfea07987bb2
Create Date: 2024-09-25 13:28:10.586399

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "e7dd1f869034"
down_revision: Union[str, None] = "dfea07987bb2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sequencing_uploads",
        "lotus2_report_task_id",
        existing_type=mysql.INTEGER(display_width=11),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sequencing_uploads",
        "lotus2_report_task_id",
        existing_type=sa.String(length=255),
        type_=mysql.INTEGER(display_width=11),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
