"""Add field using_scripps to sequencing_uploads

Revision ID: edd64ee8fd53
Revises: 0067468deeec
Create Date: 2024-07-15 10:43:04.464397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'edd64ee8fd53'
down_revision: Union[str, None] = '0067468deeec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sequencing_uploads', sa.Column('using_scripps', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sequencing_uploads', 'using_scripps')
    # ### end Alembic commands ###
