"""Remove SequencingRun from sequencing_samples table

Revision ID: f14349630eca
Revises: a72e6d642384
Create Date: 2025-04-07 08:39:35.431669

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "f14349630eca"
down_revision: Union[str, None] = "a72e6d642384"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequencing_samples", "SequencingRun")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequencing_samples",
        sa.Column("SequencingRun", mysql.VARCHAR(length=255), nullable=True),
    )
    # ### end Alembic commands ###
