"""Delete fields for gz_unzipped progress

Revision ID: f213796342df
Revises: 29fac04b58a6
Create Date: 2024-02-08 10:27:14.679294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f213796342df'
down_revision: Union[str, None] = '29fac04b58a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'gz_unziped_progress')
    op.drop_column('uploads', 'gz_unziped')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('gz_unziped', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('uploads', sa.Column('gz_unziped_progress', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
