"""Add md5 file to sequencing

Revision ID: f7dff9fff09b
Revises: 211d91f7158e
Create Date: 2024-07-30 11:43:56.635501

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f7dff9fff09b"
down_revision: Union[str, None] = "211d91f7158e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequencing_files_uploaded",
        sa.Column("md5", sa.String(length=50), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequencing_files_uploaded", "md5")
    # ### end Alembic commands ###
