"""Add field reviewed_by_admin on v2

Revision ID: fad56b066c2b
Revises: a359cd8996b1
Create Date: 2024-08-05 08:11:07.596030

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fad56b066c2b"
down_revision: Union[str, None] = "a359cd8996b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequencing_uploads",
        sa.Column("reviewed_by_admin", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequencing_uploads", "reviewed_by_admin")
    # ### end Alembic commands ###
